demo:
  core:
    homeParam:
      path: "./tmp/"
    slotDuration: 10000 # 10 s
    genesis:
      genesisSeed: "GromakNaRechke"
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 2
      distribution:
        - equal: 1000
        - specific:
          - - "LL4qKn62hrdLh1vkyiidEFLfCaAngaVmtu3ipGVSubhackXS4pXNbeDC"
            - 100
