demo: &demo
  core: &demo-core
    slotDuration: 10000 # 10 s
    fee:
      money:
        type: linear
        coeffs:
          minimal: 0.000010
          multiplier: 0.1
      publication:
        type: linear
        coeffs:
          minimal: 0.000010
          multiplier: 1
    genesis: &demo-genesis
      genesisSeed: "GromakNaRechke"
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 4
      distribution:
        - equal: 1000
        - specific:
            # Faucet
            3BAyX5pNrN2UzxPZhrFAocCti3nVRUZRk7CZtudT2iLhGH6T1eq5FzqEuk: 1000
            # Educator which uses ./run/educator.key file
            3BAyX5pQbc8bg6SEz3RkYjEUs71PjLobGVRNq2bhHX2YZQaRPbeLyfz9Y8: 1000
            # Correponds to "educator-1" seed
            3BAyX5pV23FWHExksqiRsPpYYZZsSpygcnhQSrrDW72oFM7RZhTwVMxD4t: 1000
            # Test key #1, secret: ffRB5uhVEV24NXsYUuw1irt9HF5i5IRWJXHJzagXU8Y=
            3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe: 1000
            # Test key #2, secret: fOhZOFr6SSnYv1/xfKPPMHdWLdQDboysJ4Q794Gezmw=
            3BAyX5pSiFerJgLsJZ9XyoBDMHPtq3NLqm5AGPcBpba6W644zSiSWy3vVr: 1000
  witness:
    db:
      path: "/var/db/dscp-witness"
      clean: false
    logging:
      default-name: "witness"
      config:
        backends:
        - type: stderr
        - type: syslog
          app-name: "witness"
        min-level: Debug

  educator:
    logging:
      default-name: "educator"
      config:
        backends:
        - type: stderr
        - type: syslog
          app-name: "educator"
        min-level: Debug

  faucet:
    logging:
      default-name: "faucet"
      config:
        backends:
        - type: stderr
        - type: syslog
          app-name: "faucet"
        min-level: Debug

singleton:
  <<: *demo
  core:
    <<: *demo-core
    genesis:
      <<: *demo-genesis
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 2

clusterCi:
   <<: *demo
   core:
     <<: *demo-core
     slotDuration: 20000
     genesis:
       <<: *demo-genesis
       genesisSeed: "clusterCiGenesis"
       governance:
         type: committeeOpen
         secret: "clusterCiCommittee"
         n: 3
       distribution:
         - equal: 3
         - specific:
            # faucet
            3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe: 100500

alpha:
  <<: *demo
  core:
    <<: *demo-core
    slotDuration: 20000 # 20s
    genesis:
      <<: *demo-genesis
      genesisSeed: "disciplina-alpha"
      governance:
        type: committeeClosed
        participants:
          - 3BAyX5pV5b1oAzyas5pcPdicQDUrAipz1fY5CnQLS2Xnzo5wcSBDBCCMxN
          - 3BAyX5pSN9HyzCr4K4ggmoUt95TuRmGzAZYm5JhVyPgtMjYRk3D7uW1bQ2
          - 3BAyX5pPp5upFgiCT8TSCNv6E31QniwguFVchoDTDEnUg36PKkfVm6ZVWf
          - 3BAyX5pNqALCrjBnZDSR25QyNGcfpvpoKetEJsuMCHWqr3zQpZ1LEEP3ye
          - 3BAyX5pSUJ2HhGbdzDo74M1o7Ng1ntqo6gAmuCmNHnvF18JpEJqTUQgfTX
      distribution:
        - equal: 5
        - specific:
            # faucet
            3BAyX5pMm4mhu7vVRF7skUXLaBoCwneW5C56YPCAtgMT2eJ7H8YBd3vMVU: 20000000
