demo: &demo
  core: &demo-core
    slotDuration: 10000 # 10 s
    genesis: &demo-genesis
      genesisSeed: "GromakNaRechke"
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 4
      distribution:
        - equal: 1000
        - specific:
          - # Faucet
            - LL4qKn62hrdLh1vkyiidEFLfCaAngaVmtu3ipGVSubhackXS4pXNbeDC
            - 100
          - # Test key #1, secret: ffRB5uhVEV24NXsYUuw1irt9HF5i5IRWJXHJzagXU8Y=
            - LL4qKoASaEwZGfvoQCPa2xGv3LKJQVCxaRw73p61Bj6tD8CSDcgkANf6
            - 100
          - # Test key #2, secret: fOhZOFr6SSnYv1/xfKPPMHdWLdQDboysJ4Q794Gezmw=
            - LL4qKqwvLDw4eKXTt5tpCZytoyaMVVbRmVRCo1HL8zwPaNWDxBnLpKoJ
            - 100

singleton:
  <<: *demo
  core:
    <<: *demo-core
    genesis:
      <<: *demo-genesis
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 1

clusterCi:
   <<: *demo
   core:
     <<: *demo-core
     slotDuration: 20000
     genesis:
       <<: *demo-genesis
       genesisSeed: "clusterCiGenesis"
       governance:
         type: committeeOpen
         secret: "clusterCiCommittee"
         n: 3
       distribution:
         - equal: 3
         - specific:
           - # faucet
             - "LL4qKmuUkqHGMSXpBKzDyA9g2VCAwVNLRbfGtXeHv55MCeewkKcpLGNR"
             - 100500

alpha:
  <<: *demo
  core:
    <<: *demo-core
    slotDuration: 20000 # 20s
    genesis:
      <<: *demo-genesis
      genesisSeed: "disciplina-alpha"
      governance:
        type: committeeClosed
        participants:
          - "LL4qKmQ2bqfmZzVwFYWVtgcFM2Gbku3vD8zrsq7wSGxcHHeG2Sg2dMF7"
          - "LL4qKrReykH2tVzJ3URSd3iq77Bhua5rbdHvjQ92VLnUMyXY7vp5YbAV"
          - "LL4qKq3Q31CurnN2DRKuC6iim3JQc46cnT6fL3V6qJAi979zV4zKM34J"
          - "LL4qKsoarNjaVHLxM8pD5Yoo5kwsEeUWm8E5iACF993t3R41yYbuwa6a"
      distribution:
        - equal: 4
        - specific:
          - # faucet
            - "LL4qKkm96QnsHmNpYPrfRmToHEZfYForxUKwtJ8CmnbGwzN4TpP4gPx8"
            - 20000000
