demo: &demo
  core: &demo-core
    slotDuration: 10000 # 10 s
    fee:
      money:
        type: linear
        coeffs:
          minimal: 10
          multiplier: 0.1
      publication:
        type: linear
        coeffs:
          minimal: 10
          multiplier: 1
    genesis: &demo-genesis
      genesisSeed: "GromakNaRechke"
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 4
      distribution:
        - equal: 1000
        - specific:
          - # Faucet
            - 3BAyX5pNrN2UzxPZhrFAocCti3nVRUZRk7CZtudT2iLhGH6T1eq5FzqEuk
            - 1000
          - # Test key #1, secret: ffRB5uhVEV24NXsYUuw1irt9HF5i5IRWJXHJzagXU8Y=
            - 3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe
            - 1000
          - # Test key #2, secret: fOhZOFr6SSnYv1/xfKPPMHdWLdQDboysJ4Q794Gezmw=
            - 3BAyX5pSiFerJgLsJZ9XyoBDMHPtq3NLqm5AGPcBpba6W644zSiSWy3vVr
            - 1000

singleton:
  <<: *demo
  core:
    <<: *demo-core
    genesis:
      <<: *demo-genesis
      governance:
        type: committeeOpen
        secret: "opencommittee"
        n: 2

clusterCi:
   <<: *demo
   core:
     <<: *demo-core
     slotDuration: 20000
     genesis:
       <<: *demo-genesis
       genesisSeed: "clusterCiGenesis"
       governance:
         type: committeeOpen
         secret: "clusterCiCommittee"
         n: 3
       distribution:
         - equal: 3
         - specific:
           - # faucet
             - 3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe  # TO BE REPLACED
             - 100500

alpha:
  <<: *demo
  core:
    <<: *demo-core
    slotDuration: 20000 # 20s
    genesis:
      <<: *demo-genesis
      genesisSeed: "disciplina-alpha"
      governance:
        type: committeeClosed
        participants:
          - 3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe  # TO BE REPLACED
      distribution:
        - equal: 4
        - specific:
          - # faucet
            - 3BAyX5pPvmtsKAyDhtfeUZ1beJdFZzHLTHt6nHrzdGcpfagpgeysRNPyMe  # TO BE REPLACED
            - 20000000
