<<: !include "./hpack/module.yaml"

name: disciplina
description: A blockchain system for education

library:
  <<: *lib-common

  dependencies:
    - aeson
    - autoexporter
    - array
    - AVL
    - bytestring
    - containers
    - componentm
    - cryptonite
    - data-default
    - direct-sqlite
    - exceptions
    - formatting
    - fmt
    - free
    - hashable
    - interpolatedstring-perl6
    - lens
    - loot-base
    - loot-log
    - loot-network
    - log-warper
    - memory
    - monad-control
    - mtl
    - optparse-applicative
    - random
    - reflection
    - rocksdb-haskell
    - serialise
    - serokell-util
    - snowdrop
    - sqlite-simple
    - stm
    - template-haskell
    - text
    - text-format
    - time
    - time-units
    - unliftio

tests:
  disciplina-test:
    <<: *test-common

    dependencies:
      - AVL
      - bytestring
      - containers
      - cryptonite
      - disciplina
      - data-default
      - hspec
      - lens
      - tasty
      - tasty-hspec
      - tasty-discover
      - time
      - QuickCheck
      - quickcheck-instances

executables:
  disciplina-witness:
    <<: *exec-common
    source-dirs: witness
    dependencies:
      - bytestring
      - disciplina
      - formatting
      - loot-log
      - time-units
      - optparse-applicative
      - random
      - unliftio
  disciplina-educator:
    <<: *exec-common
    source-dirs: educator
    dependencies:
      - disciplina
      - formatting
      - loot-log
      - optparse-applicative
      - unliftio
