resolver: lts-10.8

packages:
- '.'
- 'tools'

nix:
  shell-file: shell.nix

extra-deps:
- ether-0.5.1.0
- log-warper-1.8.11
- o-clock-0.1.1
- pretty-tree-0.1.0.0
- serokell-util-0.8.0
- time-units-1.0.0
- universum-1.1.0

- git: https://github.com/serokell/kademlia.git
  commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master

- git: https://github.com/thoughtpolice/hs-ed25519
  # We're waiting on next release
  commit: da4247b5b3420120e20451e6a252e2a2ca15b43c

- git: https://github.com/serokell/cardano-sl
  commit: e01c3730e1a3cf46296c3e3decffc6e780e2092c
  subdirs:
    - networking

# These three are needed for cardano-sl-networking
- git: https://github.com/serokell/network-transport-tcp
  commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  
- git: https://github.com/serokell/network-transport
  commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

- git: https://github.com/avieth/network-transport-inmemory
  commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a

- git: git@github.com:serokell/auth-data-structures.git
  commit: bed9a644c90085f14700ca2f660bd2ac1f2b06d6

- git: git@github.com:serokell/snowdrop.git
  commit: 3c7f938aef06be21bad46165c5d6f32f5f41d91c

- git: https://github.com/Heimdell/rocksdb-haskell.git
  commit: 0c1f446799d3738598a5d51ebc031bbbfd2d78f8

- git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
  commit: 49f501a082d745f3b880677220a29cafaa181452

# Needed to build `cardano-sl-networking` with newer GHC
ghc-options:
  cardano-sl-networking: -fno-warn-redundant-constraints

apply-ghc-options: everything
