resolver: lts-11.17

packages:
- 'core'
- 'witness'
- 'educator'
- 'tools'
- 'wallet'
- 'faucet'

nix:
  shell-file: shell.nix

extra-deps:
- aeson-options-0.0.0
- base58-bytestring-0.1.0
- cryptonite-openssl-0.7
- pretty-tree-0.1.0.0
- time-units-1.0.0
- componentm-0.0.0.2
- serokell-util-0.8.0
- formatting-6.2.5
- typed-process-0.2.2.0
- teardown-0.5.0.0
- universum-1.1.0
- safe-exceptions-0.1.7.0
- servant-auth-0.3.2.0
- servant-auth-server-0.4.0.0

- git: https://github.com/serokell/auth-data-structures.git
  commit: f9a0cd66f443d7b0e04a3c8ae8d475f8344b823b

- git: https://github.com/serokell/direct-sqlite.git
  commit: 333a2b2cf113e115ea2ec450dc706d3f47ee54e4

- git: https://github.com/serokell/blockchain-util.git
  commit: 4d8e26e7f1f00449082444ebcdf8ecd6bf422843 # dscp/release-alpha
  subdirs:
    - snowdrop-core
    - snowdrop-util
    - snowdrop-block
    - snowdrop-execution

- git: https://github.com/serokell/rocksdb-haskell.git
  commit: 2dd6b4ffdc4edb86b477273ee3c8416a1520f4e1

- git: https://github.com/serokell/lootbox.git
  commit: 34e389808e34f1cfa56f456773682325bed56d17
  subdirs:
    - code/base
    - code/config
    - code/log
    - code/network
    - code/prelude

- git: https://github.com/serokell/ariadne.git
  commit: ab1af6d30de2147c340b401a738a00ec4c41dd49
  subdirs:
    - ariadne/core
    - knit
    - ui/cli-lib
    - ui/vty-lib

# for ariadne
- loc-0.1.3.2
- brick-0.38
- named-0.1.0.0
- ntype-0.1.0.0
- vty-5.22

# Forced by lootbox #
- base-noprelude-4.10.1.0
# - log-warper-1.8.9 - overriden above
# - serokell-util-0.6.0 - overriden above
- vinyl-0.8.1.1

# using master, because 0.2.0.0 causes segfaults
- git: https://github.com/well-typed/cborg
  commit: 37de2c0ae6bc7fa53f24f8d13748a7c370da9149
  subdirs:
  - cborg
  - serialise

- git: https://github.com/int-index/caps
  commit: 2f46fc6d5480bdef0a17f64359ad6eb29510dba4

# for caps
- git: https://github.com/mokus0/dependent-sum
  commit: f8909cb323b4ffa63af6c4e7cb3a9745e6199080

# for monitoring
- git: https://github.com/serokell/mon.git
  commit: 19d35c9895468c22397187420fe9e63379aef4db

# Lootbox dependencies end #

# for snowdrop, will be removed
- pretty-terminal-0.1.0.0

apply-ghc-options: everything
