resolver:
    https://raw.githubusercontent.com/serokell/lootbox/db765836e61f11350519d95ca3a0cb74d0b5a94c/snapshot.yaml

packages:
- '.'
- 'tools'

nix:
  shell-file: shell.nix

extra-deps:
- serialise-0.2.0.0
- cborg-0.2.0.0
- ether-0.5.1.0
- log-warper-1.8.11
- o-clock-0.1.1
- pretty-tree-0.1.0.0
- serokell-util-0.8.0
- time-units-1.0.0
- componentm-0.0.0.2
- rio-0.1.2.0
- typed-process-0.2.2.0
- teardown-0.5.0.0
- unliftio-0.2.7.0
- universum-1.1.0
- base-noprelude-4.10.1.0

- git: https://github.com/serokell/kademlia.git
  commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master

- git: https://github.com/thoughtpolice/hs-ed25519
  # We're waiting on next release
  commit: da4247b5b3420120e20451e6a252e2a2ca15b43c

- git: https://github.com/serokell/cardano-sl
  commit: e01c3730e1a3cf46296c3e3decffc6e780e2092c
  subdirs:
    - networking

# These three are needed for cardano-sl-networking
- git: https://github.com/serokell/network-transport-tcp
  commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  
- git: https://github.com/serokell/network-transport
  commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

- git: https://github.com/avieth/network-transport-inmemory
  commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a

- git: git@github.com:serokell/auth-data-structures.git
  commit: 3bd0cbc7ac0408f897f11746dbd245e3f8437bbb

- git: git@github.com:serokell/snowdrop.git
  commit: ac5c7cf3cff367982c4f973c15472b2cc2209186
  subdirs:
    - snowdrop

- git: https://github.com/serokell/rocksdb-haskell.git
  commit: 2dd6b4ffdc4edb86b477273ee3c8416a1520f4e1

- git: https://github.com/serokell/lootbox.git
  commit: f287dd6cfe29707b28cc0418e8aa099de3bfbe77
  subdirs:
    - code/prelude
    - code/log

# Needed to build `cardano-sl-networking` with newer GHC
ghc-options:
  cardano-sl-networking: -fno-warn-redundant-constraints

apply-ghc-options: everything
