resolver: lts-10.7

packages:
- '.'
- 'tools'

nix:
  shell-file: shell.nix

# TODO: this is kinda dangerous
allow-newer: true

extra-deps:
- aeson-options-0.0.0
- base58-bytestring-0.1.0
- log-warper-1.8.11
- pretty-tree-0.1.0.0
- servant-0.14.1
- servant-server-0.14.1
- time-units-1.0.0
- componentm-0.0.0.2
- rio-0.1.2.0
- serokell-util-0.8.0
- typed-process-0.2.2.0
- teardown-0.5.0.0
- unliftio-0.2.7.0

- git: https://github.com/serokell/auth-data-structures.git
  commit: 3bd0cbc7ac0408f897f11746dbd245e3f8437bbb

- git: git@github.com:serokell/snowdrop.git
  commit: ac5c7cf3cff367982c4f973c15472b2cc2209186
  subdirs:
    - snowdrop

- git: https://github.com/serokell/rocksdb-haskell.git
  commit: 2dd6b4ffdc4edb86b477273ee3c8416a1520f4e1

- git: https://github.com/serokell/lootbox.git
  commit: 9b803ba99ce0970766bf5496a855289408daad23
  subdirs:
    - code/base
    - code/log
    - code/network
    - code/prelude

# Forced by lootbox #
- base-noprelude-4.10.1.0
# - log-warper-1.8.9 - overriden above
- serialise-0.2.0.0
# - serokell-util-0.6.0 - overriden above
- vinyl-0.8.1.1
- universum-1.1.0

- git: https://github.com/int-index/caps
  commit: 2f46fc6d5480bdef0a17f64359ad6eb29510dba4

# for caps
- git: https://github.com/mokus0/dependent-sum
  commit: f8909cb323b4ffa63af6c4e7cb3a9745e6199080

# for log-warper
- o-clock-0.1.1

# for serialise
- cborg-0.2.0.0
# Lootbox dependencies end #

apply-ghc-options: everything
