resolver: lts-18.23

packages:
- 'core'
# - 'witness'  # No more custom public chain
- 'educator'
- 'multi-educator'
- 'tools'
# - 'wallet'  # Removed: this wallet is not necessary really anymore
# - 'faucet'
- 'pdfs'

extra-deps:
- aeson-options-0.0.0
- beam-core-0.9.0.0
- beam-migrate-0.5.0.0
- beam-postgres-0.5.0.0
- pretty-tree-0.1.0.0
# - serokell-util-0.10.0
- teardown-0.5.0.1
- servant-quickcheck-0.0.10.0
- HList-0.5.0.0
- union-0.1.2

- git: https://github.com/serokell/servant-util.git
  commit: ee9b1aa75011554626ddbbb72e9125f617e688d9
  subdirs:
    - servant-util
    - servant-util-beam-pg

# - git: https://github.com/serokell/avl-plus.git
#   commit: 3fb3933f4f11f282e8c498d128c3e5c79518ea9b

# - git: https://github.com/serokell/zipp.git
#   commit: ec15b334355784b4b6a052ab21108c3d6eaceff0

# - git: https://github.com/serokell/log-warper.git
#   commit: a6dd74a1085e8c6d94a4aefc2a036efe30f6cde5

# - git: https://github.com/serokell/blockchain-util.git
#   commit: a6428c6841e7002605a115002f58eff78ff9f128 # volhovm/dscp193
#   subdirs:
#     # - snowdrop-core
#     - snowdrop-util
#     # - snowdrop-block

# - git: https://github.com/serokell/rocksdb-haskell.git
#   commit: 2dd6b4ffdc4edb86b477273ee3c8416a1520f4e1

# Required by lootbox (loot-log)
- co-log-0.4.0.1
- co-log-sys-0.1.1.0

# In version 1.2.1.1 function `createTempDirectory` implemented in a way which does
# not suit for concurrent use from multiple processes.
# This fork is temporary-1.3 with version lowered to 1.2.9
# (otherwise too many dependant packages refuse to build).
- git: https://github.com/serokell/temporary.git
  commit: 102ed4671dd78c5d271f09756681aac2a41b6717

# Fixes missing resources cleanup in case of async exception.
- git: https://github.com/serokell/Haskell-componentm.git
  commit: 7dc2850e50b095e384bc4d5216e0ff0c5d204438
  subdirs:
  - componentm

- git: https://github.com/flyingleafe/lootbox.git
  commit: 5f54dbd865bb8a2dc55fd6237013dae904f78d2a
  subdirs:
    - code/base
    - code/config
    - code/log
    - code/network

# - git: https://github.com/serokell/ariadne.git
#   commit: 7676f62b48e76f6d2041d3b5c07e96979e4f517f
#   subdirs:
#     - ariadne/core
#     - knit
#     - ui/cli-lib
#     - ui/vty-lib

# # for ariadne
# - loc-0.1.3.2
# - brick-0.38
# - named-0.1.0.0
# - ntype-0.1.0.0
# - vty-5.22

- git: https://github.com/int-index/caps
  commit: 37ab7699570002ff92529cf92c8ca01d5419bb7b

# for caps
# - git: https://github.com/mokus0/dependent-sum
#   commit: f8909cb323b4ffa63af6c4e7cb3a9745e6199080

# for monitoring
- git: https://github.com/serokell/mon.git
  commit: 19d35c9895468c22397187420fe9e63379aef4db

# for fixed networking
- git: https://github.com/serokell/zeromq-haskell
  commit: 714ac20981b2d346609fd896a1af4d31eb6d1162

# Lootbox dependencies end #

# for snowdrop, will be removed
# - pretty-terminal-0.1.0.0

apply-ghc-options: everything

nix:
  shell-file: shell-native.nix
