<<: !include "../hpack/module.yaml"

name: disciplina-multi-educator
description: Disciplina Multi-key educator

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - bytestring
    - containers
    - data-default
    - directory
    - direct-sqlite
    - disciplina-core
    - disciplina-witness
    - disciplina-educator
    - exceptions
    - filepath
    - fmt
    - interpolatedstring-perl6
    - jose
    - http-types
    - lens
    - loot-base
    - loot-config
    - loot-log
    - loot-network
    - mtl
    - optparse-applicative
    - o-clock
    - postgresql-simple
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - servant-auth-server
    - servant-generic
    - servant-server
    - servant-util
    - singleton-bool
    - sqlite-simple
    - template-haskell
    - text
    - text-format
    - time
    - QuickCheck
    - unliftio
    - wai
    - wai-cors

executables:
  dscp-multi-educator:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - disciplina-multi-educator
      - loot-log
      - optparse-applicative
