<<: !include "../hpack/module.yaml"

name: disciplina-wallet
description: Ariadne-based wallet for Disciplina

library:
  <<: *lib-common
  default-extensions:
    - ApplicativeDo
    - DataKinds
    - EmptyCase
    - ExistentialQuantification
    - NegativeLiterals
    - OverloadedLabels
    - TypeOperators

  build-tools:
    - autoexporter

  dependencies:
    - Earley
    - aeson
    - async
    - bytestring
    - componentm
    - directory
    - disciplina-core
    - disciplina-witness
    - filelock
    - filepath
    - knit
    - lens
    - memory
    - optparse-applicative
    - scientific
    - serialise
    - serokell-util
    - servant
    - servant-generic
    - servant-client
    - text-format
  ghc-options:
    - -Wno-unused-top-binds

executables:
  dscp-wallet:
    <<: *exec-common
    source-dirs: exec
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - ariadne-core
      - ariadne-vty-lib
      - async
      - componentm
      - containers
      - double-conversion
      - disciplina-core
      - disciplina-wallet
      - knit
      - lens
      - ntype
      - random
      - serokell-util
      - text
      - vector

  dscp-wallet-cli:
    <<: *exec-common
    source-dirs: exec-cli
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - ariadne-cli-lib
      - ariadne-core
      - async
      - componentm
      - disciplina-core
      - disciplina-wallet
      - knit
      - ntype
      - text

  dscp-wallet-qt:
    <<: *exec-common
    source-dirs: exec-qt
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - ariadne-core
      - ariadne-qt-lib
      - async
      - componentm
      - containers
      - double-conversion
      - disciplina-core
      - disciplina-wallet
      - knit
      - lens
      - ntype
      - random
      - serokell-util
      - text
      - vector
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -dynamic
