<<: !include "../hpack/module.yaml"

name:        disciplina-wallet
description: This package contains Ariadne-based wallet for Disciplina

library:
  <<: *lib-common
  default-extensions:
    - ApplicativeDo
    - DataKinds
    - EmptyCase
    - ExistentialQuantification
    - NegativeLiterals
    - OverloadedLabels
    - TypeOperators
  dependencies:
    - Earley
    - aeson
    - ansi-wl-pprint
    - async
    - bytestring
    - containers
    - directory
    - disciplina-core
    - disciplina-witness
    - filelock
    - formatting
    - haskeline
    - http-types
    - http-client
    - ii-extras
    - knit
    - lens
    - loc
    - megaparsec
    - memory
    - scientific
    - serialise
    - serokell-util
    - servant
    - servant-generic
    - servant-client
    - text
    - text-format
    - vinyl

    # for Ariadne/UI/Vty
    - Hclip
    - ansi-terminal
    - brick
    - named
    - text-zipper
    - transformers
    - vty
  ghc-options:
    - -Wno-unused-top-binds

executables:
  disciplina-wallet:
    <<: *exec-common
    source-dirs: app
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - disciplina-core
      - disciplina-wallet
      - disciplina-witness
      - ii-extras
      - knit
      - optparse-applicative
      - text

  disciplina-wallet-vty:
    <<: *exec-common
    source-dirs: app-vty
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - containers
      - double-conversion
      - disciplina-core
      - disciplina-wallet
      - disciplina-witness
      - ii-extras
      - knit
      - lens
      - optparse-applicative
      - serokell-util
      - text
      - vector
