<<: !include "../hpack/module.yaml"

name:        disciplina-wallet
description: This package contains Ariadne-based wallet for Disciplina

library:
  <<: *lib-common
  default-extensions:
    - ApplicativeDo
    - DataKinds
    - EmptyCase
    - ExistentialQuantification
    - NegativeLiterals
    - OverloadedLabels
    - TypeOperators
  dependencies:
    - Earley
    - aeson
    - bytestring
    - directory
    - disciplina-core
    - disciplina-witness
    - filelock
    - ii-extras
    - knit
    - lens
    - memory
    - scientific
    - serialise
    - serokell-util
    - servant
    - servant-generic
    - servant-client
    - text-format
  ghc-options:
    - -Wno-unused-top-binds

executables:
  disciplina-wallet:
    <<: *exec-common
    source-dirs: app
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - ariadne-cli-lib
      - ariadne-core
      - disciplina-core
      - disciplina-wallet
      - disciplina-witness
      - ii-extras
      - knit
      - optparse-applicative
      - text

  disciplina-wallet-vty:
    <<: *exec-common
    source-dirs: app-vty
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - ariadne-core
      - ariadne-vty-lib
      - containers
      - double-conversion
      - disciplina-core
      - disciplina-wallet
      - disciplina-witness
      - ii-extras
      - knit
      - lens
      - optparse-applicative
      - serokell-util
      - text
      - vector
