<<: !include "../hpack/module.yaml"

name:        disciplina-wallet
description: This package contains Ariadne-based wallet for Disciplina

library:
  <<: *lib-common
  default-extensions:
    - ApplicativeDo
    - DataKinds
    - ExistentialQuantification
  dependencies:
    - Earley
    - aeson
    - ansi-wl-pprint
    - async
    - bytestring
    - containers
    - directory
    - disciplina-core
    - disciplina-witness
    - filelock
    - formatting
    - haskeline
    - http-types
    - http-client
    - ii-extras
    - knit
    - lens
    - loc
    - megaparsec
    - memory
    - scientific
    - serialise
    - serokell-util
    - servant
    - servant-generic
    - servant-client
    - text
    - text-format
    - vinyl

executables:
  disciplina-wallet:
    <<: *exec-common
    source-dirs: app
    default-extensions:
      - DataKinds
    dependencies:
      - ansi-wl-pprint
      - disciplina-core
      - disciplina-witness
      - disciplina-wallet
      - ii-extras
      - knit
      - optparse-applicative
      - text
