<<: !include "../hpack/module.yaml"

name: disciplina-pdfs
description: Disciplina tools for work with PDFs

library:
  <<: *lib-common

  dependencies:
    - bytestring
    - base64-bytestring
    - hashable
    - pandoc

tests:
  disciplina-witness-test:
    <<: *test-common

    dependencies:
      - bytestring
      - disciplina-pdfs
      - hspec
      - QuickCheck

executables:
  dscp-inject-json-into-pdf:
    <<: *exec-common
    source-dirs: app
    dependencies:
      - disciplina-pdfs
      - bytestring
      - text
