<<: !include "../hpack/module.yaml"

name: disciplina-pdfs
description: Disciplina tools for work with PDFs

library:
  <<: *lib-common

  dependencies:
    - contravariant
    - containers
    - bytestring
    - base64-bytestring
    - directory
    - disciplina-core
    - hashable
    - path
    - path-io
    - pandoc
    - text
    - text-printer
    - time
    - typed-process
    - temporary

tests:
  disciplina-witness-test:
    <<: *test-common

    dependencies:
      - bytestring
      - disciplina-pdfs
      - hspec
      - QuickCheck

executables:
  dscp-inject-json-into-pdf:
    <<: *exec-common
    source-dirs: inject
    dependencies:
      - disciplina-pdfs
      - bytestring
      - text

  dscp-generate-test-pdf:
    <<: *exec-common
    source-dirs: test-pdf
    dependencies:
      - disciplina-pdfs
      - bytestring
      - text
