steps:
  - command: nix-build release.nix -A disciplina-hlint -o hlint.html
    agents:
      system: x86_64-linux
    artifact_paths:
    - hlint.html
    label: hlint

  - command: nix-build release.nix -A disciplina-trailing-whitespace --no-out-link
    agents:
      system: x86_64-linux
    label: trailing-whitespace

  - command: nix-build --no-out-link
    agents:
      system: x86_64-linux
    label: build

  # NOTE: Darwin builds are temporarily disabled until they are fixed
  # - command: nix-build --no-out-link
  #   agents:
  #     system: x86_64-darwin
  #   label: build-darwin

  - command: nix-build shell.nix --no-out-link
    agents:
      system: x86_64-linux
    label: shell

  # - command: nix-build shell.nix --no-out-link
  #   agents:
  #     system: x86_64-darwin
  #   label: shell-darwin

  - wait

  - command: nix-build release.nix -A disciplina-wallet-flatpak -o disciplina-wallet.flatpak
    agents:
      system: x86_64-linux
    artifact_paths:
    - disciplina-wallet.flatpak
    label: flatpak

  - command: nix-build release.nix -A disciplina-haddock -o haddock.tar.gz
    agents:
      system: x86_64-linux
    artifact_paths:
    - haddock.tar.gz
    label: haddock

  # - command: nix-build release.nix -A disciplina-wallet-macos-zip -o disciplina-wallet-macos.zip
  #   agents:
  #     system: x86_64-darwin
  #   artifact_paths:
  #   - disciplina-wallet-macos.zip
  #   label: macos-zip

  - command: nix-build specs -o specs/result
    agents:
      system: x86_64-linux
    artifact_paths:
    - specs/result/*.pdf
    label: specs

  - command: nix-build release.nix -A disciplina --no-out-link
    agents:
      system: x86_64-linux
    label: static
