steps:
  - command: scripts/lint-haskell.sh
    agents:
      system: x86_64-linux
    artifact_paths:
    - hlint.html
    label: lint-haskell

  - command: scripts/lint-trailing-whitespace.sh
    agents:
      system: x86_64-linux
    label: lint-trailing-whitespace

  - command: nix-build --no-out-link | nix-shell --run 'cachix push disciplina'
    agents:
      system: x86_64-linux
    label: build

  - command: nix-build --no-out-link | nix-shell --run 'cachix push disciplina'
    agents:
      system: x86_64-darwin
    label: build-darwin

  - command: nix-build release.nix -A disciplina-haddock -o haddock
    agents:
      system: x86_64-linux
    artifact_paths:
    - haddock/*
    label: build-haddock

  - command: nix-build release.nix -A disciplina-wallet-flatpak -o disciplina-wallet.flatpak
    agents:
      system: x86_64-linux
    artifact_paths:
    - disciplina-wallet.flatpak
    label: build-flatpak

  - command: nix-build specs -o specs/result
    agents:
      system: x86_64-linux
    artifact_paths:
    - specs/result/*.pdf
    label: build-specs
