steps:
  - command: nix-build release.nix -A disciplina-hlint -o hlint.html
    agents:
      queue: testing
      system: x86_64-linux
    artifact_paths:
    - hlint.html
    label: hlint

  - command: nix-build release.nix -A disciplina-trailing-whitespace --no-out-link
    agents:
      queue: testing
      system: x86_64-linux
    label: trailing-whitespace

  - command: nix-build --no-out-link
    agents:
      queue: testing
      system: x86_64-linux
    label: build

  - command: nix-build shell.nix --no-out-link
    agents:
      queue: testing
      system: x86_64-linux
    label: shell

  - wait

  - command: nix-build release.nix -A disciplina-wallet-flatpak -o disciplina-wallet.flatpak
    agents:
      queue: testing
      system: x86_64-linux
    artifact_paths:
    - disciplina-wallet.flatpak
    label: flatpak

  - command: nix-build release.nix -A disciplina-haddock -o haddock.tar.gz
    agents:
      queue: testing
      system: x86_64-linux
    artifact_paths:
    - haddock.tar.gz
    label: haddock

  - command: nix-build specs -o specs/result
    agents:
      queue: testing
      system: x86_64-linux
    artifact_paths:
    - specs/result/*.pdf
    label: specs

  - command: nix-build release.nix -A disciplina --no-out-link
    agents:
      queue: testing
      system: x86_64-linux
    label: static
