openapi: 3.0.0
info:
  description: >-
    This is a public HTTP API served by Disciplina Multi-Educator node
    and it covers public access to Disciplina certificates.
  version: 1.0.0
  title: Disciplina Certificates API
  termsOfService: 'https://disciplina.io/tnc.pdf'
  contact:
    email: hi@serokell.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'https://localhost:8090/api/certificates/v1'
  - url: 'http://localhost:8090/api/certificates/v1'
paths:
  /cert/{certificateId}.pdf:
    get:
      summary: Get the certificate by ID
      description: >-
        Gets the PDF certificate with FairCV JSON included as metadata by ID.
        CertificateID is obtained as `base64url("<educator-UUID>:<certificate-hash>")`,
        where `<educator-UUID>` is the UUID assigned by AAA microservice to Educator,
        and `<certificate-hash>` is a hash of certificate meta.
      operationId: getCertificate
      parameters:
        - $ref: '#/components/parameters/CertificateId'
      responses:
        200:
          description: Successful operation
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        404:
          description: Certificate with given ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrResponse'

components:
  parameters:
    CertificateId:
      in: path
      name: certificateId
      description: Full certificate ID
      required: true
      schema:
        type: string
        format: base64url

  schemas:
    ErrResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - CertificateNotFound
          description: |-
            Error type:
              * `CertificateNotFound` - Specified certificate does not exist.
