<<: !include "../hpack/module.yaml"

name: disciplina-core
description: Disciplina blockchain core functionality

library:
  <<: *lib-common

  dependencies:
    - aeson
    - aeson-options
    - autoexporter
    - bytestring
    - bytestring
    - base58-bytestring
    - containers
    - componentm
    - cryptonite
    - cryptonite-openssl
    - data-default
    - digest
    - directory
    - exceptions
    - fmt
    - hashable
    - hspec
    - log-warper
    - loot-base
    - loot-config
    - loot-log
    - lens
    - memory
    - o-clock
    - optparse-applicative
    - prettyprinter
    - QuickCheck
    - quickcheck-instances
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - serokell-util
    - servant
    - semver
    - snowdrop-util
    - stm
    - text
    - text-format
    - time
    - unix
    - unliftio
    - yaml

tests:
  disciplina-core-test:
    <<: *test-common

    dependencies:
      - bytestring
      - containers
      - disciplina-core
      - hspec
      - tasty
      - tasty-hspec
      - QuickCheck
