<<: !include "../hpack/module.yaml"

name: disciplina-faucet
description: This package contains disciplina faucet backend

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - disciplina-core
    - disciplina-witness
    - fmt
    - http-types
    - lens
    - loot-base
    - loot-config
    - loot-log
    - optparse-applicative
    - reflection
    - serokell-util
    - servant
    - servant-client
    - servant-generic
    - servant-server
    - text-format
    - unliftio
    - wai
    - wai-cors

executables:
  dscp-faucet:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      - disciplina-faucet
      - disciplina-wallet
      - disciplina-witness
      - fmt
      - lens
      - loot-base
      - loot-log
      - optparse-applicative
      - text
