# Include this file in your module's `package.yaml` to set sensible defaults
# and get access to useful utilities.
# Included verbatim to make `haskell.nix` build work

_definitions:
  _top-level:
    - &meta
        version:            '0.1.0.0'
        author:             Serokell
        maintainer:         hi@serokell.io
        copyright:          2018 TeachMePlease.com
        github:             DisciplinaOU/disciplina
        extra-source-files: [README.md]

    - &default-extensions
        - NoImplicitPrelude
        - AllowAmbiguousTypes
        - BangPatterns
        - ConstraintKinds
        - DataKinds
        - DefaultSignatures
        - DeriveDataTypeable
        - DeriveGeneric
        - EmptyCase
        - FlexibleContexts
        - FlexibleInstances
        - FunctionalDependencies
        - GeneralizedNewtypeDeriving
        - LambdaCase
        - MultiParamTypeClasses
        - MultiWayIf
        - NamedFieldPuns
        - OverloadedStrings
        - OverloadedLabels
        - PatternSynonyms
        - RankNTypes
        - RecordWildCards
        - ScopedTypeVariables
        - StandaloneDeriving
        - TemplateHaskell
        - TupleSections
        - TypeFamilies
        - TypeOperators
        - UndecidableInstances
        - ViewPatterns
        - TypeApplications

    - &dependencies
        - base
        - universum

    - &ghc-options
        - -Wall
        - -fno-warn-orphans
        - -Widentities
        - -Wincomplete-record-updates
        - -Werror

  _utils:
    - &lib-common
        source-dirs: src

        ghc-options:
          - -Wincomplete-uni-patterns

    - &test-common
        main:        Main.hs
        source-dirs: tests

        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N

    - &bench-common
        source-dirs: bench

        ghc-options:
          - -threaded

    - &exec-common
        main:        Main.hs
        ghc-options:
          - -threaded
          - -O2
          - -Wincomplete-uni-patterns

<<: *meta
default-extensions: *default-extensions
dependencies: *dependencies
ghc-options: *ghc-options

name: disciplina-educator
description: Disciplina educator

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - ansi-terminal
    - beam-core
    - beam-migrate
    - beam-postgres
    - bytestring
    - containers
    - data-default
    - disciplina-core
    - disciplina-pdfs
    # - disciplina-witness
    - directory
    - exceptions
    - filepath
    - fmt
    - interpolatedstring-perl6
    - jose
    - http-client
    - http-client-tls
    - http-media
    - http-types
    - lens
    - loot-base
    - loot-config
    - loot-log
    - loot-network
    - memory
    - memory-hexstring
    - mon
    - mtl
    - optparse-applicative
    - o-clock
    - parsec
    - path
    - path-io
    - postgresql-simple
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - servant
    - servant-auth-server
    - servant-client
    - servant-client-core
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - servant-swagger-ui-core
    - servant-util
    - servant-util-beam-pg
    # - snowdrop-util
    - swagger2
    - tagged
    - template-haskell
    - text
    - text-format
    - time
    - QuickCheck
    - generic-arbitrary
    - unliftio
    - warp
    - wai
    - wai-cors
    # - web3-solidity

tests:
  disciplina-test:
    <<: *test-common

    build-tools:
      - tasty-discover

    dependencies:
      - beam-core
      - beam-migrate
      - beam-postgres
      - bytestring
      - containers
      - cryptonite
      - data-default
      - disciplina-core
      # - disciplina-witness
      - disciplina-educator
      - disciplina-pdfs
      - directory
      - filepath
      - fmt
      - generic-arbitrary
      - hspec-core
      - hspec
      - http-types
      - interpolatedstring-perl6
      - lens
      - loot-base
      - loot-config
      - loot-log
      - postgresql-simple
      - process
      - safe-exceptions >= 0.1.4
      - servant
      - servant-client
      - servant-server
      - servant-mock
      - servant-quickcheck
      - servant-util
      - sqlite-simple
      - stm
      - tagged
      - tasty
      - tasty-hspec
      - text-format
      - tmp-postgres
      - time
      - QuickCheck
      - unliftio
      - wai

executables:
  dscp-educator:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      # - disciplina-witness
      - disciplina-educator
      - loot-log
      - optparse-applicative
