<<: !include "../hpack/module.yaml"

name: disciplina-educator
description: Disciplina educator

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - ansi-terminal
    - beam-core
    - beam-postgres
    - bytestring
    - containers
    - data-default
    - directory
    - disciplina-core
    - disciplina-witness
    - exceptions
    - filepath
    - fmt
    - interpolatedstring-perl6
    - jose
    - http-types
    - http-media
    - lens
    - loot-base
    - loot-config
    - loot-log
    - loot-network
    - memory
    - mtl
    - optparse-applicative
    - o-clock
    - postgresql-simple
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - servant-auth-server
    - servant-client
    - servant-generic
    - servant-server
    - servant-util
    - servant-util-beam-pg
    - snowdrop-util
    - template-haskell
    - text
    - text-format
    - time
    - QuickCheck
    - unliftio
    - wai
    - wai-cors

tests:
  disciplina-test:
    <<: *test-common

    build-tools:
      - tasty-discover

    dependencies:
      - beam-core
      - beam-migrate
      - beam-postgres
      - bytestring
      - containers
      - cryptonite
      - data-default
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - directory
      - fmt
      - generic-arbitrary
      - hspec-core
      - hspec
      - interpolatedstring-perl6
      - lens
      - loot-base
      - loot-config
      - loot-log
      - postgresql-simple
      - process
      - safe-exceptions >= 0.1.4
      - stm
      - tasty
      - tasty-hspec
      - text-format
      - tmp-postgres
      - time
      - QuickCheck
      - unliftio

executables:
  dscp-educator:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - loot-log
      - optparse-applicative

data-files:
  - database/*.sql
