<<: !include "../hpack/module.yaml"

name: disciplina-educator
description: Disciplina educator

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - ansi-terminal
    - beam-core
    - beam-migrate
    - beam-postgres
    - bytestring
    - containers
    - data-default
    - disciplina-core
    - disciplina-pdfs
    - disciplina-witness
    - directory
    - exceptions
    - filepath
    - fmt
    - interpolatedstring-perl6
    - jose
    - http-client
    - http-client-tls
    - http-types
    - lens
    - loot-base
    - loot-config
    - loot-log
    - loot-network
    - memory
    - mtl
    - optparse-applicative
    - o-clock
    - path
    - path-io
    - postgresql-simple
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - servant-auth-server
    - servant-client
    - servant-generic
    - servant-client-core
    - servant-server
    - servant-swagger
    - servant-util
    - servant-util-beam-pg
    - snowdrop-util
    - swagger2
    - template-haskell
    - text
    - text-format
    - time
    - QuickCheck
    - generic-arbitrary
    - unliftio
    - wai
    - wai-cors

tests:
  disciplina-test:
    <<: *test-common

    build-tools:
      - tasty-discover

    dependencies:
      - beam-core
      - beam-migrate
      - beam-postgres
      - bytestring
      - containers
      - cryptonite
      - data-default
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - disciplina-pdfs
      - directory
      - filepath
      - fmt
      - generic-arbitrary
      - hspec-core
      - hspec
      - http-types
      - interpolatedstring-perl6
      - lens
      - loot-base
      - loot-config
      - loot-log
      - postgresql-simple
      - process
      - safe-exceptions >= 0.1.4
      - servant
      - servant-client
      - servant-generic
      - servant-server
      - servant-mock
      - servant-quickcheck
      - servant-util
      - sqlite-simple
      - stm
      - tasty
      - tasty-hspec
      - text-format
      - tmp-postgres
      - time
      - QuickCheck
      - unliftio
      - wai

executables:
  dscp-educator:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - loot-log
      - optparse-applicative
