<<: !include "../hpack/module.yaml"

name: disciplina-educator
description: Disciplina educator

library:
  <<: *lib-common

  build-tools:
    - autoexporter

  dependencies:
    - aeson
    - aeson-options
    - ansi-terminal
    - beam-core
    - beam-sqlite >= 0.3.2.3
    - bytestring
    - containers
    - data-default
    - directory
    - direct-sqlite
    - disciplina-core
    - disciplina-witness
    - exceptions
    - filepath
    - fmt
    - interpolatedstring-perl6
    - jose
    - http-types
    - lens
    - loot-base
    - loot-config
    - loot-log
    - loot-network
    - memory
    - mtl
    - optparse-applicative
    - o-clock
    - reflection
    - safe-exceptions >= 0.1.4
    - serialise
    - servant-auth-server
    - servant-client
    - servant-generic
    - servant-server
    - snowdrop-util
    - sqlite-simple
    - template-haskell
    - text
    - text-format
    - time
    - QuickCheck
    - unliftio
    - wai
    - wai-cors

tests:
  disciplina-test:
    <<: *test-common

    build-tools:
      - tasty-discover

    dependencies:
      - containers
      - cryptonite
      - data-default
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - directory
      - fmt
      - generic-arbitrary
      - hspec
      - interpolatedstring-perl6
      - lens
      - loot-base
      - loot-config
      - loot-log
      - safe-exceptions >= 0.1.4
      - sqlite-simple
      - stm
      - tasty
      - tasty-hspec
      - temporary
      - text-format
      - time
      - QuickCheck
      - unliftio

executables:
  dscp-educator:
    <<: *exec-common
    source-dirs: exec
    dependencies:
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - loot-log
      - optparse-applicative
