loggerTree:
  handlers:
    - file: node.log

  severity: Info+

  witness:
    severity: Debug+

    network:
      severity: Info+

    web:
      severity: Info+

  init:
    log:
      severity: Debug+
