loggers-tree:
    witness:
        withPERROR: true
        min-level: Debug
        sub-loggers:
            network:
                min-level: Info

            web:
                min-level: Info

    init.log:
        withPERROR: true
        min-level: Debug
