<<: !include "../hpack/module.yaml"

name:        disciplina-tools
description: This package contains tools for development of Disciplina
             platform, such as simulators of cryptographic protocols.

executables:
  dscp-simulacrum:
    <<: *exec-common
    source-dirs: src/simulacrum
    dependencies:
      - mtl
  dscp-txperf:
    <<: *exec-common
    source-dirs: src/txperf
    dependencies:
      - aeson
      - aeson-options
      - bytestring
      - disciplina-core
      - disciplina-witness
      - memory
      - QuickCheck
      - optparse-applicative
      - reflection
      - serokell-util
      - servant-client
  dscp-keygen:
    <<: *exec-common
    source-dirs: src/keygen
    dependencies:
      - aeson
      - aeson-pretty
      - bytestring
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - lens
      - named
      - memory
      - optparse-applicative
      - serialise
      - text
      - word8
  dscp-faircv:
    <<: *exec-common
    source-dirs: src/faircv
    dependencies:
      - aeson
      - aeson-pretty
      - bytestring
      - containers
      - data-default
      - disciplina-core
      - disciplina-witness
      - disciplina-educator
      - lens
      - loot-log
      - o-clock
      - optparse-applicative
      - serialise
      - servant-client
      - time
      - QuickCheck
    default-extensions:
      - CPP
      - DeriveAnyClass
