<<: !include "../hpack/module.yaml"

name:        disciplina-tools
description: This package contains tools for development of Disciplina
             platform, such as simulators of cryptographic protocols.

executables:
  dscp-simulacrum:
    <<: *exec-common
    source-dirs: src/simulacrum
    dependencies:
      - mtl
  dscp-txperf:
    <<: *exec-common
    source-dirs: src/txperf
    dependencies:
      - aeson
      - aeson-options
      - bytestring
      - disciplina-core
      - disciplina-witness
      - memory
      - QuickCheck
      - optparse-applicative
      - reflection
      - serokell-util
      - servant-client